import type { Book, User, LoanEvent, Node as LibNode } from "./types"

export const mockUsers: User[] = [
  {
    id: "u1",
    display_name: "CleverRaven88",
    email: "raven@example.com",
    auth_provider: "email",
    trust_score: 92,
    community_memberships: ["c1"],
    created_at: "2024-06-01T10:00:00Z",
  },
  {
    id: "u2",
    display_name: "WanderingOwl42",
    email: "owl@example.com",
    auth_provider: "linkedin",
    trust_score: 87,
    community_memberships: ["c1"],
    created_at: "2024-07-15T14:00:00Z",
  },
  {
    id: "u3",
    display_name: "BrightFox29",
    email: "fox@example.com",
    auth_provider: "twitter",
    trust_score: 74,
    community_memberships: ["c1", "c2"],
    created_at: "2024-08-01T09:30:00Z",
  },
  {
    id: "u4",
    display_name: "CuriousDeer17",
    email: "deer@example.com",
    auth_provider: "email",
    trust_score: 95,
    community_memberships: ["c2"],
    created_at: "2024-09-10T11:00:00Z",
  },
  {
    id: "u5",
    display_name: "SwiftHawk55",
    email: "hawk@example.com",
    auth_provider: "email",
    trust_score: 68,
    community_memberships: ["c1"],
    created_at: "2024-10-05T16:00:00Z",
  },
]

export const mockNodes: LibNode[] = [
  {
    id: "n1",
    name: "Foresight Berlin Flybrary",
    type: "coworking",
    location_lat: 52.52,
    location_lng: 13.405,
    location_address: "Friedrichstrasse 68, 10117 Berlin",
    steward_id: "u1",
    public: true,
    capacity: 120,
    operating_hours: "Mon-Fri 9am-7pm",
    created_at: "2024-05-01T08:00:00Z",
  },
  {
    id: "n2",
    name: "Cafe Momentum",
    type: "cafe",
    location_lat: 52.5,
    location_lng: 13.42,
    location_address: "Torstrasse 100, 10119 Berlin",
    steward_id: "u2",
    public: true,
    capacity: 30,
    operating_hours: "Daily 8am-10pm",
    created_at: "2024-06-15T10:00:00Z",
  },
  {
    id: "n3",
    name: "Little Free Library #42",
    type: "little_free_library",
    location_lat: 52.53,
    location_lng: 13.39,
    location_address: "Invalidenstrasse 22, 10115 Berlin",
    steward_id: "u4",
    public: true,
    capacity: 15,
    created_at: "2024-07-01T12:00:00Z",
  },
]

const defaultTerms = {
  type: "borrow" as const,
  deposit_required: false,
  loan_period_days: 21,
  shipping_allowed: false,
  local_only: true,
  member_only: false,
  contact_opt_in: true,
}

export const mockBooks: Book[] = [
  {
    id: "b1",
    isbn: "9780593189481",
    title: "The Precipice",
    author: "Toby Ord",
    qr_tag_id: "qr-001",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780316484923-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf A",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b2",
    isbn: "9780199678112",
    title: "Superintelligence",
    author: "Nick Bostrom",
    qr_tag_id: "qr-002",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780199678112-L.jpg",
    current_holder_id: "u2",
    current_holder_name: "WanderingOwl42",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "With WanderingOwl42",
    availability_status: "checked_out",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
    expected_return_date: "2026-03-01T00:00:00Z",
  },
  {
    id: "b3",
    isbn: "9780525558613",
    title: "Human Compatible",
    author: "Stuart Russell",
    qr_tag_id: "qr-003",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780525558613-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf B",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b4",
    isbn: "9781101946596",
    title: "Life 3.0",
    author: "Max Tegmark",
    qr_tag_id: "qr-004",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9781101946596-L.jpg",
    current_node_id: "n2",
    current_node_name: "Cafe Momentum",
    current_location_text: "Cafe Momentum, Window Shelf",
    availability_status: "available",
    lending_terms: { ...defaultTerms, shipping_allowed: true, local_only: false },
    created_at: "2024-06-15T12:00:00Z",
  },
  {
    id: "b5",
    isbn: "9780393635829",
    title: "The Alignment Problem",
    author: "Brian Christian",
    qr_tag_id: "qr-005",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780393635829-L.jpg",
    current_holder_id: "u3",
    current_holder_name: "BrightFox29",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "With BrightFox29",
    availability_status: "checked_out",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
    expected_return_date: "2026-02-28T00:00:00Z",
  },
  {
    id: "b6",
    isbn: "9781541618626",
    title: "What We Owe the Future",
    author: "William MacAskill",
    qr_tag_id: "qr-006",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9781541618626-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf A",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b7",
    isbn: "9780140259841",
    title: "The Beginning of Infinity",
    author: "David Deutsch",
    qr_tag_id: "qr-007",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780140259841-L.jpg",
    current_node_id: "n2",
    current_node_name: "Cafe Momentum",
    current_location_text: "Cafe Momentum, Shelf 1",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-15T12:00:00Z",
  },
  {
    id: "b8",
    isbn: "9780465026562",
    title: "Godel, Escher, Bach",
    author: "Douglas Hofstadter",
    qr_tag_id: "qr-008",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780465026562-L.jpg",
    current_node_id: "n3",
    current_node_name: "Little Free Library #42",
    current_location_text: "Little Free Library #42",
    availability_status: "available",
    lending_terms: { ...defaultTerms, member_only: false },
    created_at: "2024-07-01T12:00:00Z",
  },
  {
    id: "b9",
    isbn: "9780374533557",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    qr_tag_id: "qr-009",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    current_holder_id: "u4",
    current_holder_name: "CuriousDeer17",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "With CuriousDeer17",
    availability_status: "checked_out",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
    expected_return_date: "2026-03-10T00:00:00Z",
  },
  {
    id: "b10",
    isbn: "9780804136716",
    title: "Superforecasting",
    author: "Philip Tetlock & Dan Gardner",
    qr_tag_id: "qr-010",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780804136716-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf C",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b11",
    isbn: "9780198788416",
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    qr_tag_id: "qr-011",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780198788416-L.jpg",
    current_node_id: "n2",
    current_node_name: "Cafe Momentum",
    current_location_text: "Cafe Momentum, Shelf 2",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-15T12:00:00Z",
  },
  {
    id: "b12",
    isbn: "9780143037880",
    title: "The Singularity Is Near",
    author: "Ray Kurzweil",
    qr_tag_id: "qr-012",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780143037880-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf A",
    availability_status: "available",
    lending_terms: { ...defaultTerms, deposit_required: true, deposit_amount: 10 },
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b13",
    isbn: "9781579550776",
    title: "A New Kind of Science",
    author: "Stephen Wolfram",
    qr_tag_id: "qr-013",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9781579550776-L.jpg",
    current_node_id: "n3",
    current_node_name: "Little Free Library #42",
    current_location_text: "Little Free Library #42",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-07-01T12:00:00Z",
  },
  {
    id: "b14",
    isbn: "9780143110903",
    title: "Scale",
    author: "Geoffrey West",
    qr_tag_id: "qr-014",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780143110903-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf B",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b15",
    isbn: "9781451614213",
    title: "Abundance",
    author: "Peter Diamandis & Steven Kotler",
    qr_tag_id: "qr-015",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9781451614213-L.jpg",
    current_holder_id: "u5",
    current_holder_name: "SwiftHawk55",
    current_node_id: "n2",
    current_node_name: "Cafe Momentum",
    current_location_text: "With SwiftHawk55",
    availability_status: "checked_out",
    lending_terms: defaultTerms,
    created_at: "2024-06-15T12:00:00Z",
    expected_return_date: "2026-03-05T00:00:00Z",
  },
  {
    id: "b16",
    isbn: "9780525559023",
    title: "Existential Risk",
    author: "Nick Bostrom",
    qr_tag_id: "qr-016",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780199678112-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf A",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b17",
    isbn: "9780521899260",
    title: "Global Catastrophic Risks",
    author: "Nick Bostrom & Milan Cirkovic (eds.)",
    qr_tag_id: "qr-017",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780199678112-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf C",
    availability_status: "available",
    lending_terms: { ...defaultTerms, member_only: true },
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b18",
    isbn: "9780525559108",
    title: "The Fabric of Reality",
    author: "David Deutsch",
    qr_tag_id: "qr-018",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780140259841-L.jpg",
    current_node_id: "n2",
    current_node_name: "Cafe Momentum",
    current_location_text: "Cafe Momentum, Shelf 1",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-15T12:00:00Z",
  },
  {
    id: "b19",
    isbn: "9780226458113",
    title: "The Structure of Scientific Revolutions",
    author: "Thomas S. Kuhn",
    qr_tag_id: "qr-019",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780226458113-L.jpg",
    current_node_id: "n3",
    current_node_name: "Little Free Library #42",
    current_location_text: "Little Free Library #42",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-07-01T12:00:00Z",
  },
  {
    id: "b20",
    isbn: "9780262525619",
    title: "Complexity",
    author: "Melanie Mitchell",
    qr_tag_id: "qr-020",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780262525619-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf B",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b21",
    isbn: "9780141015927",
    title: "Rationality",
    author: "Steven Pinker",
    qr_tag_id: "qr-021",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780141015927-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf A",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b22",
    isbn: "9780143122012",
    title: "The Better Angels of Our Nature",
    author: "Steven Pinker",
    qr_tag_id: "qr-022",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780143122012-L.jpg",
    current_node_id: "n2",
    current_node_name: "Cafe Momentum",
    current_location_text: "Cafe Momentum, Shelf 2",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-15T12:00:00Z",
  },
  {
    id: "b23",
    isbn: "9780521288842",
    title: "Evolution and the Theory of Games",
    author: "John Maynard Smith",
    qr_tag_id: "qr-023",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780521288842-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf C",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b24",
    isbn: "9781422121030",
    title: "The Origin of Wealth",
    author: "Eric Beinhocker",
    qr_tag_id: "qr-024",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9781422121030-L.jpg",
    current_node_id: "n3",
    current_node_name: "Little Free Library #42",
    current_location_text: "Little Free Library #42",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-07-01T12:00:00Z",
  },
  {
    id: "b25",
    isbn: "9780198734628",
    title: "The Age of Em",
    author: "Robin Hanson",
    qr_tag_id: "qr-025",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780198734628-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf A",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b26",
    isbn: "9780465065707",
    title: "The Master Algorithm",
    author: "Pedro Domingos",
    qr_tag_id: "qr-026",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780465065707-L.jpg",
    current_node_id: "n2",
    current_node_name: "Cafe Momentum",
    current_location_text: "Cafe Momentum, Shelf 1",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-15T12:00:00Z",
  },
  {
    id: "b27",
    isbn: "9780525427575",
    title: "Enlightenment Now",
    author: "Steven Pinker",
    qr_tag_id: "qr-027",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780525427575-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf B",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b28",
    isbn: "9781250107817",
    title: "Factfulness",
    author: "Hans Rosling",
    qr_tag_id: "qr-028",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9781250107817-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf C",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "b29",
    isbn: "9781439171226",
    title: "The Moral Landscape",
    author: "Sam Harris",
    qr_tag_id: "qr-029",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9781439171226-L.jpg",
    current_node_id: "n3",
    current_node_name: "Little Free Library #42",
    current_location_text: "Little Free Library #42",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-07-01T12:00:00Z",
  },
  {
    id: "b30",
    isbn: "9780385530460",
    title: "The Future of Humanity",
    author: "Michio Kaku",
    qr_tag_id: "qr-030",
    cover_image_url: "https://covers.openlibrary.org/b/isbn/9780385530460-L.jpg",
    current_node_id: "n1",
    current_node_name: "Foresight Berlin Flybrary",
    current_location_text: "Foresight Berlin Flybrary, Shelf A",
    availability_status: "available",
    lending_terms: defaultTerms,
    created_at: "2024-06-01T12:00:00Z",
  },
]

export const mockLoanEvents: LoanEvent[] = [
  {
    id: "e1",
    event_type: "checkout",
    book_id: "b2",
    book_title: "Superintelligence",
    user_id: "u2",
    user_display_name: "WanderingOwl42",
    timestamp: "2026-02-08T14:30:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e2",
    event_type: "checkout",
    book_id: "b5",
    book_title: "The Alignment Problem",
    user_id: "u3",
    user_display_name: "BrightFox29",
    timestamp: "2026-02-06T10:15:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e3",
    event_type: "return",
    book_id: "b1",
    book_title: "The Precipice",
    user_id: "u1",
    user_display_name: "CleverRaven88",
    timestamp: "2026-02-05T16:45:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e4",
    event_type: "checkout",
    book_id: "b9",
    book_title: "Thinking, Fast and Slow",
    user_id: "u4",
    user_display_name: "CuriousDeer17",
    timestamp: "2026-02-03T09:00:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e5",
    event_type: "checkout",
    book_id: "b1",
    book_title: "The Precipice",
    user_id: "u1",
    user_display_name: "CleverRaven88",
    timestamp: "2026-01-15T11:20:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e6",
    event_type: "return",
    book_id: "b4",
    book_title: "Life 3.0",
    user_id: "u5",
    user_display_name: "SwiftHawk55",
    timestamp: "2026-01-10T14:00:00Z",
    location_text: "Cafe Momentum",
  },
  {
    id: "e7",
    event_type: "checkout",
    book_id: "b4",
    book_title: "Life 3.0",
    user_id: "u5",
    user_display_name: "SwiftHawk55",
    timestamp: "2025-12-20T10:30:00Z",
    location_text: "Cafe Momentum",
  },
  {
    id: "e8",
    event_type: "checkout",
    book_id: "b15",
    book_title: "Abundance",
    user_id: "u5",
    user_display_name: "SwiftHawk55",
    timestamp: "2026-02-10T08:00:00Z",
    location_text: "Cafe Momentum",
  },
  {
    id: "e9",
    event_type: "return",
    book_id: "b8",
    book_title: "Godel, Escher, Bach",
    user_id: "u3",
    user_display_name: "BrightFox29",
    timestamp: "2026-01-28T17:30:00Z",
    location_text: "Little Free Library #42",
  },
  {
    id: "e10",
    event_type: "checkout",
    book_id: "b8",
    book_title: "Godel, Escher, Bach",
    user_id: "u3",
    user_display_name: "BrightFox29",
    timestamp: "2026-01-07T09:15:00Z",
    location_text: "Little Free Library #42",
  },
  {
    id: "e11",
    event_type: "return",
    book_id: "b6",
    book_title: "What We Owe the Future",
    user_id: "u2",
    user_display_name: "WanderingOwl42",
    timestamp: "2025-12-30T15:45:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e12",
    event_type: "checkout",
    book_id: "b6",
    book_title: "What We Owe the Future",
    user_id: "u2",
    user_display_name: "WanderingOwl42",
    timestamp: "2025-12-09T11:00:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e13",
    event_type: "return",
    book_id: "b10",
    book_title: "Superforecasting",
    user_id: "u4",
    user_display_name: "CuriousDeer17",
    timestamp: "2025-12-15T13:30:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e14",
    event_type: "checkout",
    book_id: "b10",
    book_title: "Superforecasting",
    user_id: "u4",
    user_display_name: "CuriousDeer17",
    timestamp: "2025-11-24T10:00:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e15",
    event_type: "transfer",
    book_id: "b7",
    book_title: "The Beginning of Infinity",
    user_id: "u1",
    user_display_name: "CleverRaven88",
    timestamp: "2025-11-15T16:00:00Z",
    location_text: "Cafe Momentum",
    previous_holder_id: "u1",
    new_holder_id: "u3",
    notes: "Transferred at Cafe Momentum meetup",
  },
  {
    id: "e16",
    event_type: "return",
    book_id: "b7",
    book_title: "The Beginning of Infinity",
    user_id: "u3",
    user_display_name: "BrightFox29",
    timestamp: "2025-12-01T09:00:00Z",
    location_text: "Cafe Momentum",
  },
  {
    id: "e17",
    event_type: "report_damaged",
    book_id: "b13",
    book_title: "A New Kind of Science",
    user_id: "u1",
    user_display_name: "CleverRaven88",
    timestamp: "2025-10-20T14:00:00Z",
    location_text: "Little Free Library #42",
    notes: "Minor water damage on cover, pages fine",
  },
  {
    id: "e18",
    event_type: "checkout",
    book_id: "b12",
    book_title: "The Singularity Is Near",
    user_id: "u1",
    user_display_name: "CleverRaven88",
    timestamp: "2025-10-01T10:00:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e19",
    event_type: "return",
    book_id: "b12",
    book_title: "The Singularity Is Near",
    user_id: "u1",
    user_display_name: "CleverRaven88",
    timestamp: "2025-10-21T10:00:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
  {
    id: "e20",
    event_type: "checkout",
    book_id: "b3",
    book_title: "Human Compatible",
    user_id: "u4",
    user_display_name: "CuriousDeer17",
    timestamp: "2025-09-15T11:30:00Z",
    location_text: "Foresight Berlin Flybrary",
  },
]
